builders:
  fields_generator:
    import: "package:sculptor/fields_builder.dart"
    builder_factories: ["fieldBuilder"]
    build_extensions: {".dart": [".hjson"]}
    auto_apply: dependents
    build_to: source
